project_id = "pqdllrerdufpxnjyvuzi"

[functions.youtube-search]
verify_jwt = true

[functions.generate-lyrics]
verify_jwt = true

[functions.translate-word]
verify_jwt = false

[functions.generate-daily-phrases]
verify_jwt = true

[functions.generate-roleplay]
verify_jwt = true

[functions.add-xp]
verify_jwt = true
